name: methylation_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - numpy=2.0.2
  - numba=0.60.0
  - scikit-learn=1.6.1
  - umap-learn=0.5.9.post2
  - pandas=2.3.3
  - pyarrow=22.0.0
  - colorcet=3.1.0
  - geoparse=2.0.4
  - openpyxl=3.1.5
  - plotnine=0.15.1
  - requests=2.32.5
  - tqdm=4.67.1
prefix: /Users/benjaminemert/miniconda3/envs/methylation_env
